name: Build docker image
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master
      - develop

jobs:
  push:
    name: "docker push (smasher_${{ github.ref_name }})"
    runs-on: "self-hosted"
    environment:
     name: ${{ github.ref_name == 'master' && 'production' || 'development' }}
     url: ${{ github.ref_name == 'master' && 'https://smasher.fleebs.gg/' || 'https://dev.smasher.fleebs.gg/' }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.8.2"
          buildkitd-flags: --debug
      - name: 'Login to Fleebs.GG Docker Registry 🤞'
        uses: docker/login-action@v2
        with:
          registry: "registry.docker.fleebs.gg"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          ecr: false
      - uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/arm64
          file: ./Dockerfile
          tags: "registry.docker.fleebs.gg/fleebs/smasher:${{ github.ref_name }}"
